### ISSUE TITLE
Предложение по улучшению Newgramm

### ISSUE THREAD

**Issue by userdev01rgithub** [Nytrock/Newgramm#1]
### Тип улучшения

Другое

### Предложение

Не нашел документацию для API. Грустно

Ну, хотя бы методы в postman или в swagger накидайте. 

### Обладание техническими знаниями.

Да

**Comment by Nytrock** [comment]
Документация по API была сделана - https://github.com/Nytrock/Newgramm/wiki

**Comment by userdev01rgithub** [comment]
В документации не указан формат авторизации. По какому протоколу происходит авторизация?

**Comment by Nytrock** [comment]
Без понятия
